version: '2.1'

services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - ${PROM_PORT}:9090
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      - monitoring
      - https
  metrics_exporter:
    build:
      context: metrics_exporter
    ports:
      - ${EXPORTER_PORT}:8080
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge
  https:
    external:
      name: ${HTTPS_NETWORK}
volumes:
  prometheus_data: {}
  grafana_data: {}
