version: '2.1'

services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - ${PROM_PORT}:9090
    networks:
      - monitoring
      - database_network
    environment:
      - VIRTUAL_HOST=${PROM_DOMAIN}
      - VIRTUAL_PORT=${PROM_PORT}
      - LETSENCRYPT_HOST=${PROM_DOMAIN}
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - VIRTUAL_HOST=${GRAFANA_DOMAIN}
      - VIRTUAL_PORT=${GRAFANA_PORT}
      - LETSENCRYPT_HOST=${GRAFANA_DOMAIN}
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      - monitoring
      - https

networks:
  monitoring:
    driver: bridge
  https:
    external:
      name: ${HTTPS_NETWORK}
  database_network:
    external:
      name: database_network
volumes:
  prometheus_data: {}
  grafana_data: {}
