version: "3.8"

services:
  prometheus:
    image: prom/prometheus:v2.20.1
    restart: always
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - ${PROM_PORT}:9090
    networks:
      - monitoring
      - database_network

  grafana:
    image: grafana/grafana:7.1.5
    restart: always
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      - monitoring
      - https

networks:
  monitoring:
    driver: bridge
  https:
    name: ${HTTPS_NETWORK}
    external: true
  database_network:
    name: ${DATABASE_NETWORK}
    external: true

volumes:
  prometheus_data:
  grafana_data:
